package tokobuku.view;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import tokobuku.impl.PegawaiImpl;
import tokobuku.model.Pegawai;

/**
 *
 * @author Rosyid Iz
 */
public class PegawaiPanelView extends javax.swing.JPanel {

    protected final int index;
    protected final PegawaiImpl pegawaiImpl;
    protected Pegawai pegawai;

    /**
     * Creates new form PegawaiPanelView
     *
     * @param index
     * @param pegawaiImpl
     */
    protected PegawaiPanelView(int index, PegawaiImpl pegawaiImpl) {
        initComponents();
        this.index = index;
        this.pegawaiImpl = pegawaiImpl;
    }

    protected void setPegawai(Pegawai pegawai) {
        this.pegawai = pegawai;
        nama_pegawai.setText(this.pegawai.getNama());
        labelNoTelp.setText(this.pegawai.getTelepon());
        shift.setText(this.pegawai.getShif());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sep = new javax.swing.JSeparator();
        nama_pegawai = new javax.swing.JTextField();
        labelNoTelp = new javax.swing.JLabel();
        shift = new javax.swing.JLabel();
        labelShift = new javax.swing.JLabel();

        setBackground(new java.awt.Color(65, 65, 65));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3)));
        setMaximumSize(new java.awt.Dimension(210, 210));
        setMinimumSize(new java.awt.Dimension(210, 210));
        setPreferredSize(new java.awt.Dimension(210, 210));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sep.setForeground(new java.awt.Color(200, 200, 200));
        add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 10));

        nama_pegawai.setEditable(false);
        nama_pegawai.setBackground(new java.awt.Color(65, 65, 65));
        nama_pegawai.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        nama_pegawai.setForeground(new java.awt.Color(255, 255, 255));
        nama_pegawai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama_pegawai.setText("Nama Pegawai");
        nama_pegawai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nama_pegawai.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nama_pegawai.setEnabled(false);
        nama_pegawai.setRequestFocusEnabled(false);
        add(nama_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 40));

        labelNoTelp.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        labelNoTelp.setForeground(new java.awt.Color(222, 222, 222));
        labelNoTelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoTelp.setText("08XXXXXXXXXX");
        add(labelNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 30));

        shift.setFont(new java.awt.Font("Bebas", 0, 24)); // NOI18N
        shift.setForeground(new java.awt.Color(255, 255, 255));
        shift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shift.setText("Shift");
        add(shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        labelShift.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelShift.setForeground(new java.awt.Color(200, 200, 200));
        labelShift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelShift.setText("Shift:");
        add(labelShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel labelShift;
    private javax.swing.JTextField nama_pegawai;
    private javax.swing.JSeparator sep;
    private javax.swing.JLabel shift;
    // End of variables declaration//GEN-END:variables
}

class AddPegawaiPanelView {

    protected PegawaiPanelView pegawaiPanelV;
    private JTextField tf_namaPegawai;
    private JTextField tf_alamatPegawai;
    private JTextField tf_notelpPegawai;
    private JTextField tf_unamePegawai;
    private JLabel labelIDPegawai;
    private JRadioButton rb_kasir;
    private JRadioButton rb_admin;
    private JRadioButton rb_pagi;
    private JRadioButton rb_sore;
    private final JPanel panelDTPegawai;
    private JButton btnEditPegawai;
    private JButton btnHapusPegawai;
    private JButton btnEditPassword;

    public AddPegawaiPanelView(int index, PegawaiImpl pegawaiImpl, Pegawai pegawai, JPanel panelDTPegawai) {
        pegawaiPanelV = new PegawaiPanelView(index, pegawaiImpl);
        pegawaiPanelV.setPegawai(pegawai);
        this.panelDTPegawai = panelDTPegawai;
    }

    public void init(
            JTextField tf_namaPegawai,
            JTextField tf_alamatPegawai,
            JTextField tf_notelpPegawai,
            JTextField tf_unamePegawai,
            JLabel labelIDPegawai,
            JRadioButton rb_kasir,
            JRadioButton rb_admin,
            JRadioButton rb_pagi,
            JRadioButton rb_sore,
            JButton btnEditPegawai,
            JButton btnHapusPegawai,
            JButton btnEditPassword
    ) {
        this.tf_namaPegawai = tf_namaPegawai;
        this.tf_alamatPegawai = tf_alamatPegawai;
        this.tf_notelpPegawai = tf_notelpPegawai;
        this.tf_unamePegawai = tf_unamePegawai;
        this.labelIDPegawai = labelIDPegawai;
        this.rb_kasir = rb_kasir;
        this.rb_admin = rb_admin;
        this.rb_pagi = rb_pagi;
        this.rb_sore = rb_sore;
        this.btnEditPegawai = btnEditPegawai;
        this.btnHapusPegawai = btnHapusPegawai;
        this.btnEditPassword = btnEditPassword;

        pegawaiPanelV.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Runnable runnable = () -> {
                    if (panelDTPegawai.isVisible()) {
                        boolean loop = true;
                        while (loop) {
                            if (btnEditPegawai.getText().equalsIgnoreCase("edit")) {
                                if (pegawaiPanelV.index == Integer.parseInt(labelIDPegawai.getText())) {
                                    pegawaiPanelV.setBackground(new Color(65, 65, 65));
                                    panelDTPegawai.setVisible(false);
                                } else {
                                    for (int i = pegawaiPanelV.getParent().getComponentCount() - 1; i >= 0; i--) {
                                        if (pegawaiPanelV.getParent().getComponent(i).getBackground().equals(new Color(55, 55, 55))) {
//                                if (i != pegawaiPanelV.index) {
                                            pegawaiPanelV.getParent().getComponent(i).setBackground(new Color(65, 65, 65));
                                        } else if (i == pegawaiPanelV.index) {
                                            pegawaiPanelV.setBackground(new Color(55, 55, 55));
                                        }
                                    }
                                    setDetailPegawai();
                                }
                                loop = false;
                            } else {
                                Pegawai oldP = pegawaiPanelV.pegawaiImpl.listPegawais.get(Integer.parseInt(labelIDPegawai.getText()));
                                Pegawai newP = new Pegawai();
                                newP.setIdKasir(oldP.getIdKasir());
                                newP.setNama(tf_namaPegawai.getText());
                                newP.setAlamat(tf_alamatPegawai.getText());
                                newP.setTelepon(tf_notelpPegawai.getText());
                                String shif = rb_pagi.isSelected() ? "Pagi" : "Sore";
                                newP.setShif(shif);
                                newP.setUsername(tf_unamePegawai.getText());
                                newP.setPassword(oldP.getPassword());
                                newP.setSalt(oldP.getSalt());
                                String akses = rb_admin.isSelected() ? "admin" : "kasir";
                                newP.setAkses(akses);

                                boolean same = oldP.getIdKasir() == newP.getIdKasir()
                                        && oldP.getNama().equals(newP.getNama())
                                        && oldP.getAlamat().equals(newP.getAlamat())
                                        && oldP.getTelepon().equals(newP.getTelepon())
                                        && oldP.getUsername().equals(newP.getUsername())
                                        && oldP.getAkses().equals(newP.getAkses())
                                        && oldP.getPassword().equals(newP.getPassword())
                                        && oldP.getShif().equals(newP.getShif())
                                        && oldP.getSalt().equals(newP.getSalt());

                                if (!same) {
                                    CustomJPanelView jOpt = new CustomJPanelView();
                                    jOpt.setPanel("black");
                                    int aksi = jOpt.displayConfirmDialog(
                                            panelDTPegawai.getParent(),
                                            "jika Anda melanjutkan. Anda akan kehilangan\n"
                                            + "semua data draf Anda. apakah Anda yakin?",
                                            "Data Belum Tersimpan");
                                    switch (aksi) {
                                        case 0:
                                            noChange();
                                            break;
                                        default:
                                            loop = false;
                                    }
                                } else {
                                    noChange();
                                }
                            }
                        }
                    } else {
                        setDetailPegawai();
                        pegawaiPanelV.setBackground(new Color(55, 55, 55));
                        panelDTPegawai.setVisible(true);
                    }
                };
                runnable.run();
            }
        });
    }

    private synchronized void setDetailPegawai() {
        tf_namaPegawai.setText(pegawaiPanelV.pegawai.getNama());
        tf_alamatPegawai.setText(pegawaiPanelV.pegawai.getAlamat());
        tf_notelpPegawai.setText(pegawaiPanelV.pegawai.getTelepon());
        tf_unamePegawai.setText(pegawaiPanelV.pegawai.getUsername());
        labelIDPegawai.setText(String.valueOf(pegawaiPanelV.index));
        if (pegawaiPanelV.pegawai.getAkses().equalsIgnoreCase("kasir")) {
            rb_kasir.setSelected(true);
        } else {
            rb_admin.setSelected(true);
        }
        if (pegawaiPanelV.pegawai.getShif().equalsIgnoreCase("pagi")) {
            rb_pagi.setSelected(true);
        } else {
            rb_sore.setSelected(true);
        }
    }

    private synchronized void noChange() {
        btnEditPegawai.setText("EDIT");
        tf_namaPegawai.setEnabled(false);
        tf_alamatPegawai.setEnabled(false);
        tf_notelpPegawai.setEnabled(false);
        tf_unamePegawai.setEnabled(false);
        rb_pagi.setEnabled(false);
        rb_sore.setEnabled(false);
        rb_admin.setEnabled(false);
        rb_kasir.setEnabled(false);
        btnEditPassword.setVisible(false);
    }
}
